name: Release

on:
  push:
    tags:
      - 'v*'

# Sets permissions for release creation
permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Build for production
        run: npm run build
        
      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            ## What's New
            - Latest features and improvements
            - Bug fixes and security updates
            - Performance optimizations
            
            ## Installation
            Visit [acepaste.xyz](https://acepaste.xyz) to use the latest version.
            
            ## Changelog
            See the [full changelog](https://github.com/sugarcypher/Ace-Paste-Cleaner/compare/${{ github.event.before }}...${{ github.ref }}) for detailed changes.
          draft: false
          prerelease: false
